### ISSUE TITLE
fixed-width docs

### ISSUE THREAD

**Issue by ltalirz** [yakutovicha/aiida-lsmo#19]
For some reason, the docs of aiida-qe are fixed-width
https://aiida-quantumespresso.readthedocs.io/en/latest/
(see https://github.com/aiidateam/aiida-quantumespresso/blob/develop/docs/source/conf.py)

while the one on e.g. aiida-diff is full-width
https://aiida-diff.readthedocs.io/en/latest/
(see https://github.com/aiidateam/aiida-diff/blob/master/docs/source/conf.py)

Looking at the `conf.py` files, it's not obvious to me where this comes from.

Anyhow, if we want it, it's [quite straightforward](https://stackoverflow.com/a/33626140/1069467) to achieve this.

**Comment by danieleongari** [comment]
Thanks, I solved it in the alpha-2 PR
