### ISSUE TITLE
ASE 3.20 chokes on P1 symmetry

### ISSUE THREAD

**Issue by ltalirz** [yakutovicha/aiida-lsmo#46]
A couple of examples from https://github.com/lsmo-epfl/aiida-lsmo/tree/develop/examples currently fail because the latest ASE version 3.20 and above chokes on the CIF files (encountered by @mpougin for multistage workchain with aluminium and H2O):

```
 ase.spacegroup.spacegroup.SpacegroupNotFoundError: invalid spacegroup `P 1`, setting `None` not found in data base 
```

We will need to figure out whether the fault is in the CIF files, e.g. see related issue https://github.com/danieleongari/CURATED-COFs/issues/16

Until then we may need to limit the ase version to "ase<3.20" as a workaround.

Mentioning @danieleongari @yakutovicha

**Comment by yakutovicha** [comment]
sorry, I didn't know it would be closed automatically.

**Comment by ltalirz** [comment]
the ASE version has been limited in the setup.json for the time being

Leaving this open since we may want to check what the underlying issue here is
