### ISSUE TITLE
Implement Feynman-Hibbs potential for the FFBuilder (?)

### ISSUE THREAD

**Issue by danieleongari** [yakutovicha/aiida-lsmo#64]
The Feynmann-Hibbs (FH) potential is needed to account for the quantum-wave nature of small particles.
In practice this is only influential for light adsorbent (i.e., only H2, maybe He) at low temperature (e.g., 77K), and results in a weaker energy of interaction, due to the delocalized atomic entity.
When comparing H2 isotherms at 77K this gets relevant only at higher pressure, where the H2-H2 interactions gets more relevant: the H2-MOF interaction (which contributes to the kH = initial slope of the isotherm) seems to be less affected. See e.g., http://xlink.rsc.org/?DOI=C7EE02477K
![image](https://user-images.githubusercontent.com/25899092/102008191-087b7d00-3d2f-11eb-9064-98792d120991.png)

The formula implemented in Raspa 
![image](https://user-images.githubusercontent.com/25899092/102008213-2ea11d00-3d2f-11eb-8a14-47d54e8ba148.png)

is an extension of the Lennard-Jones interaction, that becomes non-negligible only when both the atoms are light (low reduced mass) and the temperature is low. 
When using the `FEYNMAN-HIBBS-LENNARD-JONES` potential in Raspa ONLY for H2 (as we currently do) for the mixing rules 
Raspa assumes that the mass of the other atom is very high, and the reduced mass converges to 2:
> (2*100)/(2+100) ~ 2
Note that this is anyway making the FH correction non-negligible: this becomes negligible only if the temperature is hig, or BOTH the particles are heavy (i.e., high reduced mass).

This is reasonable for all the atoms of the frameworks except H, for which the reduced mass of H2-H is 
> (2*1)/(2+1) = 0.66

Consider that the H2-H2 reduced mass is:
> (2*2)/(2+2) = 1

and that there are many more H2-H2 interaction when approaching saturation, which is the important range to evaluate gas storage. Therefore, our assumption to exclude H2-MOF FH contribute seems reasonable.
To account for the FH interactions for all the atoms pairs we should use in the `force_field_mixing_rules.def`, the `FEYNMAN-HIBBS-LENNARD-JONES` potential and specify, after LJ's sigma and epsilon, the reduced mass for the self interactions, which is half the atomic weight of the element. It is not very difficult to implement this, but require some reasoning on how the user needs to specify FH, and what to do if there are other particles in the system, like united-atoms beads, that required some informed values (which can anyhow be derived from the `pseudo_atoms.def`).

### Summary
This FH correction for the whole system can be tweaked by some option like `separate_interactions`, but we should think carefully, and it does not seem urgent if, at the end of the day, a careful evaluation of the reduced mass for H2-MOF interactions is negligible

@sauradeep93 is currently evaluating what is the contribute of FH in the H2-MOF interactions, and if these can be reasonably neglected or not.

**Comment by kjappelbaum** [comment]
just saw this issue in the dashboard and remembered https://arxiv.org/abs/1408.0608

**Comment by danieleongari** [comment]
As @sauradeep93 investigated for MOF-5, for H2 adsorption at 77K, the contribute of Feynmann-Hibbs on other interactions than H2-H2, can be reasonably neglected for sake of simplicity of implementation.

We can expect this conclusion not to hold true for frameworks with a large amount of H atoms (e.g., a polymer having a lot of linear alkane chains), at low pressure (where the H2-framework interactions are predominant) ,but that's not typical for the rigid materials we deal with.

![image](https://user-images.githubusercontent.com/25899092/104717417-929d7380-5729-11eb-87cb-0fd641b957e2.png)
