### ISSUE TITLE
cp2k binding energy calculations yield unphysical bsse

### ISSUE THREAD

**Issue by mpougin** [yakutovicha/aiida-lsmo#75]
The DFT energies calculated with the BindingSite workchain result in extremely high corrected binding energies (~ 2 to 3 * -10^5 kJ/mol) due to unphysical bsse. I experienced this in all of my calculations this year. I just run the test wc (https://github.com/lsmo-epfl/aiida-lsmo/blob/develop/examples/run_BindingSiteWorkChain_MOF74_CO2.py) using raspa-4467e14@fidis-serial andcp2k-5.1@helvetios. I get the following cp2k output dict:
`{                                                                                                                                                                               "binding_energy_bsse": -2178989.9351219,                                                                                                                                    "binding_energy_corr": 2178956.7936331,                                                                                                                                     "binding_energy_dispersion": -21.361676400578,                                                                                                                              "binding_energy_raw": -33.141488855341,                                                                                                                                     "binding_energy_unit": "kJ/mol",                                                                                                                                            "motion_opt_converged": false,                                                                                                                                              "motion_step_info": {                                                                                                                                                           "dispersion_energy_au": [                                                                                                                                                       -0.16233019269837,                                                                                                                                                          -0.16234970471036,                                                                                                                                                          -0.16231227878718,                                                                                                                                                          -0.16224767612766,                                                                                                                                                          -0.16222322395047,                                                                                                                                                          -0.16221221242885                                                                                                                                                       ],                                                                                                                                                                          "energy_au": [                                                                                                                                                                  -829.91930582395,                                                                                                                                                           -829.92128447225,                                                                                                                                                           -829.92147671786,                                                                                                                                                           -829.92159367314,                                                                                                                                                           -829.921674636,                                                                                                                                                             -829.92167681991                                                                                                                                                        ],                                                                                                                                                                          "max_grad_au": [                                                                                                                                                                null,                                                                                                                                                                       0.0067308872,                                                                                                                                                               0.0044478517,                                                                                                                                                               0.0067341529,                                                                                                                                                               0.0008866158,                                                                                                                                                               0.0018017187                                                                                                                                                            ],                                                                                                                                                                          "max_step_au": [                                                                                                                                                                null,                                                                                                                                                                       0.0387788492,                                                                                                                                                               0.0279071904,                                                                                                                                                               0.0531515546,                                                                                                                                                               0.0174067956,                                                                                                                                                               0.0074783668                                                                                                                                                            ],                                                                                                                                                                          "rms_grad_au": [                                                                                                                                                                null,                                                                                                                                                                       0.0007732628,                                                                                                                                                               0.0005362628,                                                                                                                                                               0.0007456283,                                                                                                                                                               0.0001156248,                                                                                                                                                               0.0002175644                                                                                                                                                            ],                                                                                                                                                                          "rms_step_au": [                                                                                                                                                                null,                                                                                                                                                                       0.0052556901,                                                                                                                                                               0.0042090882,                                                                                                                                                               0.0048061243,                                                                                                                                                               0.0021768516,                                                                                                                                                               0.0010439191                                                                                                                                                            ],                                                                                                                                                                          "scf_converged": [                                                                                                                                                              true,                                                                                                                                                                       true,                                                                                                                                                                       true,                                                                                                                                                                       true,                                                                                                                                                                       true,                                                                                                                                                                       true                                                                                                                                                                    ]                                                                                                                                                                       }                                                                                                                                                                       }                                           `

I think there is some intrinsic problem with the calculation, @ltalirz or @danieleongari maybe someone with a better understanding of the code can take a look

**Comment by ltalirz** [comment]
As mentioned [in the forum](https://groups.google.com/g/cp2k/c/wgTW3Ak7Nso/m/jz-ZVNUHAQAJ) this can happen when the `GHOST` atoms are missing.

This is my mistake - in the following commit I accidentally replaced `get_kinds_with_ghost_section` by `get_kinds`
https://github.com/lsmo-epfl/aiida-lsmo/commit/e3b2babc39a8850dbee0466aee2b696924e8cac5#diff-eb5fed9f81158586ba48a37091048a7ec787ddb752f94cf853c710d8df9544ea

@mpougin Would you mind undoing this replacement in a pull request?

We do check the binding energy in a test
https://github.com/lsmo-epfl/aiida-lsmo/blob/7f58b7b3fd15cfb60a4b97211cdc959652947278/examples/test_Cp2kBindingEnergy_CO2_MOF74.py#L82

but perhaps this particular key does not include the BSSE?
Which key would include it?

**Comment by ltalirz** [comment]
> Which key would include it?

The key would be `binding_energy_corr` - I'll add it to the test

**Comment by mpougin** [comment]
thank you @ltalirz
