### ISSUE TITLE
Single-Bead Molecules with UFF

### ISSUE THREAD

**Issue by ElMouba** [yakutovicha/aiida-lsmo#97]
CH4 is a single bead molecule. The methane.def file created includes 1 atom-like description and it's called CH4-Sp3. 
This is not a problem when using TraPPE to describe the CH4 interactions. However, it is a problem when using UFF. In the latter case, aiida creates the same methane.def file and extracts the Lennard-Jones parameters for C_.

The issue appears every time we use RASPA to run calculations. Which means, the error can be found in every workchain where we run Widom Insertion and GCMC calculations.

**Comment by danieleongari** [comment]
Hi, I did not get your problem, please clarify better which FF you are building.
It seems to me you want to use `TraPPE-mod` force field with "separate interactions".
https://github.com/lsmo-epfl/aiida-lsmo/blob/0999ccec3e445cfd0dfd37a65ab013299a5f7d51/aiida_lsmo/calcfunctions/ff_data.yaml#L642-L661

**Comment by ElMouba** [comment]
Hello Daniele,

Yes, you are absolutely right. 
I am sorry for the misunderstanding.

**Comment by ElMouba** [comment]
Although, it is there for CH4 but not for ethane, methane, methanol and ethanol.

**Comment by danieleongari** [comment]
I'm happy it is solved,
please feel free to make a PR for adding a similar model for the other molecules you need!

**Comment by ElMouba** [comment]
Awesome.

Thank you so much
